services:
  pokepicker:
    image: pokepicker:latest
    ports: 
      - "8080:3000"
    environment:
      - PORT=3000
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - C:\Users\tanne\OneDrive\Documents\volumes\pokepicker:/var/lib/mysql