services:
  pokepicker:
    image: pokepicker:latest
    ports: 
      - "8080:3000"
    environment:
      - PORT=3000
      - POKEAPI_URL_GQL=https://graphql.pokeapi.co/v1beta2
    # depends_on:
    #   - mysql
  # mysql:
  #   image: mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #   volumes:
  #     - C:\Users\tanne\OneDrive\Documents\volumes\pokepicker:/var/lib/mysql